redis:
  port: 6379
  host: localhost

fetch_cache:
  use_cache: true
  expiration: 604800 # pages expire in one week
  save_to_disk: false

event_crawler:
  meetup:
    skip: false
    filename: hot-sf.json
  eventbrite:
    skip: false
    filename: hot-sf-eventbrite.json

meetup:
  api_key: asdf

algolia:
  app_id: asdf
  admin_api_key: asdf

aws:
  accessKeyId: asdf
  secretAccessKey: asdf
  bucket: aws-website-sfhotevents-rtg2c
